#主配置文件
spring:
  application:
    name: fasaxi-eva
  # 激活环境配置
  profiles:
    active: local
  # 文件编码 UTF8
  mandatory-file-encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  # 服务端口
  port: 8801

mybatis-plus:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
  # mapper路径位置
  mapper-locations: classpath:mapper/*.xml

# 文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    #operations-sorter: order
  group-configs:
    - group: 'openApi'
      display-name: '对外API'
      paths-to-match: '/**'
      packages-to-scan: cn.acecandy.fasaxi.eva.control
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: 对外API
    - name: 标题2
      locations: classpath:markdown1/*
      group: 对外API

common-game:
  init:
    enable: false
  groupDoor:
    enable: false
  wd:
    enable: false
  cc:
    enable: false
  xm:
    enable: false
  ktcfh:
    enable: false
  ktccy:
    enable: false